### ISSUE TITLE
OMV5 安裝求助

### ISSUE THREAD

**Issue by jackcctse** [ttys3/filebrowser-enhanced#5]
OMV5利用portainer安装了，但似乎启动不成功。请问是什么问题？

在/config下是有 database.db这个文件的。

```
-rw------- 1 semson users 16384 Apr 15 00:35 database.db
drwxrwxr-x 2 semson users  4096 Apr 14 01:18 ssl
```

以下是log。

```
-------------------------------------,
,
User uid:    1000,
User gid:    100,
-------------------------------------,
,
setup /config permission ...,
/config owner set to 1000:100,
init config ...,
https disabled.,
init config done.,
time="2020-04-15 00:33:56" level=info msg="Using config file: /home/app/.filebrowser.toml",
File Browser  v2.9.2/26d67127,
Built For   : linux/amd64,
Go Version  : go1.14.2,
Release Date: 20200414-0305,
time="2020-04-15 00:34:00" level=info msg="Using config file: /config/.filebrowser.toml",
time="2020-04-15 00:34:00" level=fatal msg="failed to open db file: /config/database.db, err: no such device",
time="2020-04-15 00:34:03" level=info msg="Using config file: /home/app/.filebrowser.toml",
File Browser  v2.9.2/26d67127,
Built For   : linux/amd64,
Go Version  : go1.14.2,
Release Date: 20200414-0305,
time="2020-04-15 00:34:07" level=info msg="Using config file: /config/.filebrowser.toml",
time="2020-04-15 00:34:07" level=fatal msg="failed to open db file: /config/database.db, err: no such device",
```

**Comment by ttys3** [comment]
FBE默认以docker 环境变量指定的env PUID:PGID 权限运行。
确保配置目录这个PUID的用户要有权限。具体见dockerhub 文档。

**Comment by jackcctse** [comment]
謝謝回覆。我的權限應該是正確的，如下：
```
root@omvplay:~# id semson
uid=1000(semson) gid=100(users) groups=100(users)

root@omvplay:~# ls -l /srv/5f555b9a-8d0f-42b4-847e-1a5804b365b0/AppData/
total 40
drwxrwxr-x 3 semson users 4096 Apr 15 01:13 filebroswer

root@omvplay:~# ls -l /srv/5f555b9a-8d0f-42b4-847e-1a5804b365b0/AppData/filebroswer/
total 20
-rwxrwxr-x 1 semson users 16384 Apr 15 00:35 database.db
drwxrwxr-x 2 semson users  4096 Apr 14 01:18 ssl

```

**Comment by jackcctse** [comment]
我的安装环境是OMV5 + Portainer。原版file brower的docker镜是成功安装的。

**Comment by jackcctse** [comment]
各项调试后发现是目录映射出了问题，移除所有映射后镜像能启动。然后我又试着把路径由 /srv/5f555b9a-8d0f-42b4-847e-1a5804b365b0换成 /sharedfolders，仍然失败,,, 

已排除权限，我试过用PUID/PGID=0，甚至chmod -R 777了。 
而且docker是能找到映射的路径，/config 对应的host目录在缺省的情况docker会自己建立及修正权引。

是不是镜像有兼容问题？

```
docker run -d \
--name filebrowser-hwacc \
--restart=unless-stopped \
-e PUID=1000 \
-e PGID=100 \
-e SSL=off \
-e UMASK_SET=000 \
-e WEB_PORT=8082 \
-p 0.0.0.0:8082:8082 \
-v /sharedfolders/Downloads:/myfiles \
-v /sharedfolders/AppData/filebroswer-hwacc:/config \
80x86/filebrowser:amd64
```

**Comment by ttys3** [comment]
运行镜像 一定要指定tag. 你不要直接使用`amd64` 这样的tag.

**Comment by ttys3** [comment]
另外，`cat /etc/os-release` 看看你的debian是什么版本。
暂时没有证据表明是镜像问题。

**Comment by jackcctse** [comment]
谢谢灯大的耐心回覆。镜像是v2.9.2的，为了排除问题，我删了本地的镜像用2.9.2-amd64这个tag重新拉了镜像回来，问题依然。以下是相关指令：

`docker pull 80x86/filebrowser:2.9.2-amd64`

`docker run -d \
--name filebrowser-hwacc \
--restart=unless-stopped \
-e PUID=1000 \
-e PGID=100 \
-e SSL=off \
-e UMASK_SET=000 \
-e WEB_PORT=8082 \
-p 0.0.0.0:8082:8082 \
-v /sharedfolders/Downloads:/myfiles \
-v /sharedfolders/AppData/filebroswer-hwacc:/config \
80x86/filebrowser:2.9.2-amd64`

我也试了 2.9.1-amd64, 也是不行；用Portainer手动添加container结果一样。我用的OMV5是基于Debian 10的。后面有空试试用虚拟机装OMV4试试。

`root@omvplay:/sharedfolders/AppData# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@omvplay:/sharedfolders/AppData# `

**Comment by jackcctse** [comment]
灯大，我有发现了。我映射的目录/sharedfolders 或/5f555b9a-8d0f-42b4-847e-1a5804b365b0 是MergeFS(Union Filesystem)建立的，FBE不支持；原版 FB是OK的。我现在直接映射"实际"硬盘路径是能启动，但这样要一个个目录去映射有点繁覆，能不能改良？

另外查看log发现ffmpeg有个error，好像硬解没有生效？播放效果很不流畅，怎样能确认有没有使用硬解？我的cpu是J1900, 在 jellyfin上硬解OK。硬件映射我用了/dev/dri/renderD128, 额外加上/dev/dri/card0也是一样。

```
current time: Sat Apr 18 13:27:00 CST 2020,
usermod: no changes,
,
-------------------------------------,
_   _                   ____  __  __ ,
| \ | | __ _ _ __   ___ |  _ \|  \/  |,
|  \| |/ _` | "_ \ / _ \| | | | |\/| |,
| |\  | (_| | | | | (_) | |_| | |  | |,
|_| \_|\__,_|_| |_|\___/|____/|_|  |_|,
,
,
Brought to you by nanodm.net,
We gratefully accept donations at:,
https://nanodm.net/donate,
-------------------------------------,
GID/UID,
-------------------------------------,
,
User uid:    1000,
User gid:    100,
-------------------------------------,
,
setup /config permission ...,
/config owner set to 1000:100,
init config ...,
https disabled.,
init config done.,
warning: volume /myfiles is not mapped correctly.,
time="2020-04-18 13:27:04" level=info msg="Using config file: /home/app/.filebrowser.toml",
File Browser  v2.9.2/26d67127,
Built For   : linux/amd64,
Go Version  : go1.14.2,
Release Date: 20200414-0305,
time="2020-04-18 13:27:08" level=info msg="Using config file: /config/.filebrowser.toml",
time="2020-04-18 13:27:08" level=info msg="GraphicsMagick init",
time="2020-04-18 13:27:08" level=info msg="http: thumbnail feature disabled",
time="2020-04-18 13:27:08" level=info msg="init search index: ignored dirs: map[]",
time="2020-04-18 13:27:08" level=info msg="indexed search has been disabled",
time="2020-04-18 13:27:08" level=info msg="checking hardware acceleration working status: \nlibva info: VA-API version 1.6.0\nlibva info: va_getDriverName() returns 0\nlibva info: User requested driver 'i965'\nlibva info: Trying to open /usr/lib/dri/i965_drv_video.so\nlibva info: Found init function __vaDriverInit_1_6\nlibva info: va_openDriver() returns 0\nvainfo: VA-API version: 1.6 (libva 2.7.1)\nvainfo: Driver version: Intel i965 driver for Intel(R) Bay Trail - 2.4.0.pre1 ()\nvainfo: Supported profile and entrypoints\n      VAProfileMPEG2Simple            :\tVAEntrypointVLD\n      VAProfileMPEG2Simple            :\tVAEntrypointEncSlice\n      VAProfileMPEG2Main              :\tVAEntrypointVLD\n      VAProfileMPEG2Main              :\tVAEntrypointEncSlice\n      VAProfileH264ConstrainedBaseline:\tVAEntrypointVLD\n      VAProfileH264ConstrainedBaseline:\tVAEntrypointEncSlice\n      VAProfileH264Main               :\tVAEntrypointVLD\n      VAProfileH264Main               :\tVAEntrypointEncSlice\n      VAProfileH264High               :\tVAEntrypointVLD\n      VAProfileH264High               :\tVAEntrypointEncSlice\n      VAProfileH264StereoHigh         :\tVAEntrypointVLD\n      VAProfileVC1Simple              :\tVAEntrypointVLD\n      VAProfileVC1Main                :\tVAEntrypointVLD\n      VAProfileVC1Advanced            :\tVAEntrypointVLD\n      VAProfileNone                   :\tVAEntrypointVideoProc\n      VAProfileJPEGBaseline           :\tVAEntrypointVLD\n",
time="2020-04-18 13:27:08" level=info msg="hls: using encoder: h264_vaapi",
time="2020-04-18 13:27:08" level=info msg="Listening on [::]:8082",
time="2020-04-18 13:29:26" level=error msg="[hls] 浙江卫视中国蓝新台歌陈奕迅《梦想天空分外蓝》官方版MV       超清.mp4: error waiting for process: exit status 1, ffmpeg err: [mjpeg_vaapi @ 0x5614afec2300] No usable encoding entrypoint found for profile VAProfileJPEGBaseline (12).\nError initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height\n",
time="2020-04-18 13:29:26" level=error msg="[hls] video: /myfiles/Media/Music Videos/浙江卫视中国蓝新台歌陈奕迅《梦想天空分外蓝》官方版MV       超清.mp4, problem serving screenshot: exit status 1",
time="2020-04-18 13:30:08" level=error msg="[hls] Hisense_Tibet.mp4: error waiting for process: exit status 1, ffmpeg err: [mjpeg_vaapi @ 0x557b02620900] No usable encoding entrypoint found for profile VAProfileJPEGBaseline (12).\nError initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height\n",
time="2020-04-18 13:30:08" level=error msg="[hls] video: /myfiles/Media/H.264 UHD Demo/Hisense_Tibet.mp4, problem serving screenshot: exit status 1",
```

**Comment by jackcctse** [comment]
补充下，我加了44(video),107(render)确保了硬件的权限，也测试了给 777 权根这两个装置仍不见效。
`root@omvplay:/dev/dri# id semson
uid=1000(semson) gid=100(users) groups=100(users),27(sudo),44(video),107(render),115(ssh)
`

**Comment by ttys3** [comment]
> 灯大，我有发现了。我映射的目录/sharedfolders 或/5f555b9a-8d0f-42b4-847e-1a5804b365b0 是MergeFS(Union Filesystem)建立的，FBE不支持；原版 FB是OK的。我现在直接映射"实际"硬盘路径是能启动，但这样要一个个目录去映射有点繁覆，能不能改良？
> 
> 另外查看log发现ffmpeg有个error，好像硬解没有生效？播放效果很卡，像是在用 cpu在转码。怎样能确认有没有使用硬解？我的cpu是J1900, 在 jellyfin上硬解OK。硬件映射我用了/dev/dri/renderD128, 额外加上/dev/dri/card0也是一样。
> 
> 駆动正確
> 
> ```
> root@omvplay:~# ls -l /dev/dri
> total 0
> drwxr-xr-x 2 root root         80 Apr 18 01:13 by-path
> crw-rw---- 1 root video  226,   0 Apr 18 01:13 card0
> crw-rw---- 1 root render 226, 128 Apr 18 01:13 renderD128
> ```
> 
> 这是FBE log
> 
> ```
> current time: Sat Apr 18 13:27:00 CST 2020,
> usermod: no changes,
> ,
> -------------------------------------,
> _   _                   ____  __  __ ,
> | \ | | __ _ _ __   ___ |  _ \|  \/  |,
> |  \| |/ _` | "_ \ / _ \| | | | |\/| |,
> | |\  | (_| | | | | (_) | |_| | |  | |,
> |_| \_|\__,_|_| |_|\___/|____/|_|  |_|,
> ,
> ,
> Brought to you by nanodm.net,
> We gratefully accept donations at:,
> https://nanodm.net/donate,
> -------------------------------------,
> GID/UID,
> -------------------------------------,
> ,
> User uid:    1000,
> User gid:    100,
> -------------------------------------,
> ,
> setup /config permission ...,
> /config owner set to 1000:100,
> init config ...,
> https disabled.,
> init config done.,
> warning: volume /myfiles is not mapped correctly.,
> time="2020-04-18 13:27:04" level=info msg="Using config file: /home/app/.filebrowser.toml",
> File Browser  v2.9.2/26d67127,
> Built For   : linux/amd64,
> Go Version  : go1.14.2,
> Release Date: 20200414-0305,
> time="2020-04-18 13:27:08" level=info msg="Using config file: /config/.filebrowser.toml",
> time="2020-04-18 13:27:08" level=info msg="GraphicsMagick init",
> time="2020-04-18 13:27:08" level=info msg="http: thumbnail feature disabled",
> time="2020-04-18 13:27:08" level=info msg="init search index: ignored dirs: map[]",
> time="2020-04-18 13:27:08" level=info msg="indexed search has been disabled",
> time="2020-04-18 13:27:08" level=info msg="checking hardware acceleration working status: \nlibva info: VA-API version 1.6.0\nlibva info: va_getDriverName() returns 0\nlibva info: User requested driver 'i965'\nlibva info: Trying to open /usr/lib/dri/i965_drv_video.so\nlibva info: Found init function __vaDriverInit_1_6\nlibva info: va_openDriver() returns 0\nvainfo: VA-API version: 1.6 (libva 2.7.1)\nvainfo: Driver version: Intel i965 driver for Intel(R) Bay Trail - 2.4.0.pre1 ()\nvainfo: Supported profile and entrypoints\n      VAProfileMPEG2Simple            :\tVAEntrypointVLD\n      VAProfileMPEG2Simple            :\tVAEntrypointEncSlice\n      VAProfileMPEG2Main              :\tVAEntrypointVLD\n      VAProfileMPEG2Main              :\tVAEntrypointEncSlice\n      VAProfileH264ConstrainedBaseline:\tVAEntrypointVLD\n      VAProfileH264ConstrainedBaseline:\tVAEntrypointEncSlice\n      VAProfileH264Main               :\tVAEntrypointVLD\n      VAProfileH264Main               :\tVAEntrypointEncSlice\n      VAProfileH264High               :\tVAEntrypointVLD\n      VAProfileH264High               :\tVAEntrypointEncSlice\n      VAProfileH264StereoHigh         :\tVAEntrypointVLD\n      VAProfileVC1Simple              :\tVAEntrypointVLD\n      VAProfileVC1Main                :\tVAEntrypointVLD\n      VAProfileVC1Advanced            :\tVAEntrypointVLD\n      VAProfileNone                   :\tVAEntrypointVideoProc\n      VAProfileJPEGBaseline           :\tVAEntrypointVLD\n",
> time="2020-04-18 13:27:08" level=info msg="hls: using encoder: h264_vaapi",
> time="2020-04-18 13:27:08" level=info msg="Listening on [::]:8082",
> time="2020-04-18 13:29:26" level=error msg="[hls] 浙江卫视中国蓝新台歌陈奕迅《梦想天空分外蓝》官方版MV       超清.mp4: error waiting for process: exit status 1, ffmpeg err: [mjpeg_vaapi @ 0x5614afec2300] No usable encoding entrypoint found for profile VAProfileJPEGBaseline (12).\nError initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height\n",
> time="2020-04-18 13:29:26" level=error msg="[hls] video: /myfiles/Media/Music Videos/浙江卫视中国蓝新台歌陈奕迅《梦想天空分外蓝》官方版MV       超清.mp4, problem serving screenshot: exit status 1",
> time="2020-04-18 13:30:08" level=error msg="[hls] Hisense_Tibet.mp4: error waiting for process: exit status 1, ffmpeg err: [mjpeg_vaapi @ 0x557b02620900] No usable encoding entrypoint found for profile VAProfileJPEGBaseline (12).\nError initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height\n",
> time="2020-04-18 13:30:08" level=error msg="[hls] video: /myfiles/Media/H.264 UHD Demo/Hisense_Tibet.mp4, problem serving screenshot: exit status 1",
> ```

```
time="2020-04-18 13:27:08" level=info msg="checking hardware acceleration working status: \nlibva info: VA-API version 1.6.0\nlibva info: va_getDriverName() returns 0\nlibva info: User requested driver 'i965'\nlibva info: Trying to open /usr/lib/dri/i965_drv_video.so\nlibva info: Found init function __vaDriverInit_1_6\nlibva info: va_openDriver() returns 0\nvainfo: VA-API version: 1.6 (libva 2.7.1)\nvainfo: Driver version: Intel i965 driver for Intel(R) Bay Trail - 2.4.0.pre1 ()\nvainfo: Supported profile and entrypoints\n      VAProfileMPEG2Simple            :\tVAEntrypointVLD\n      VAProfileMPEG2Simple            :\tVAEntrypointEncSlice\n      VAProfileMPEG2Main              :\tVAEntrypointVLD\n      VAProfileMPEG2Main              :\tVAEntrypointEncSlice\n      VAProfileH264ConstrainedBaseline:\tVAEntrypointVLD\n      VAProfileH264ConstrainedBaseline:\tVAEntrypointEncSlice\n      VAProfileH264Main               :\tVAEntrypointVLD\n      VAProfileH264Main               :\tVAEntrypointEncSlice\n      VAProfileH264High               :\tVAEntrypointVLD\n      VAProfileH264High               :\tVAEntrypointEncSlice\n      VAProfileH264StereoHigh         :\tVAEntrypointVLD\n      VAProfileVC1Simple              :\tVAEntrypointVLD\n      VAProfileVC1Main                :\tVAEntrypointVLD\n      VAProfileVC1Advanced            :\tVAEntrypointVLD\n      VAProfileNone                   :\tVAEntrypointVideoProc\n      VAProfileJPEGBaseline           :\tVAEntrypointVLD\n",
time="2020-04-18 13:27:08" level=info msg="hls: using encoder: h264_vaapi",
```
表明硬解是开启的。

**Comment by ttys3** [comment]
硬解并不是通吃。根据你的日志输出，只有符合以下编码的才能硬解：
```
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :\tVAEntrypointVLD
      VAProfileMPEG2Simple            :\tVAEntrypointEncSlice
      VAProfileMPEG2Main              :\tVAEntrypointVLD
      VAProfileMPEG2Main              :\tVAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:\tVAEntrypointVLD
      VAProfileH264ConstrainedBaseline:\tVAEntrypointEncSlice
      VAProfileH264Main               :\tVAEntrypointVLD
      VAProfileH264Main               :\tVAEntrypointEncSlice
      VAProfileH264High               :\tVAEntrypointVLD
      VAProfileH264High               :\tVAEntrypointEncSlice
      VAProfileH264StereoHigh         :\tVAEntrypointVLD
      VAProfileVC1Simple              :\tVAEntrypointVLD
      VAProfileVC1Main                :\tVAEntrypointVLD
      VAProfileVC1Advanced            :\tVAEntrypointVLD
      VAProfileNone                   :\tVAEntrypointVideoProc
      VAProfileJPEGBaseline           :\tVAEntrypointVLD
```
另外，硬解这方面一般不存在什么问题。这个都有测试过。

**Comment by ttys3** [comment]
FBE是在linux上开发完成，基本上假设这个程序是操作的ext4 或者 xfs 这种流行的文件系统。
mergerfs 或任何其它与 ext4 等不兼容的文件系统，都无法保证能正常工作。
不单是FBE，任何其它程序也一样。因为我不相信这些程序的作者在发源码的时候还会特意去测试一下mergerfs 之类的文件系统。

对于你说的mergerfs，我没有了解过。
docker官方对于bind的volume所支持的文件系统也没有相关说明。
我找到一个issue可能跟你的有点类似： https://github.com/trapexit/mergerfs/issues/463

**Comment by jackcctse** [comment]
灯大你是完全正确的。我跟mergerfs官方文档用cache.files=partial,dropcacheonclose=true去挂实，现在完全正常。再次感谢。

**Comment by ttys3** [comment]
我大概猜想到了你为什么会用像mergerfs这样的union fs.
是不是因为fbe 只允许bind 一个 /myfiles 目录？实际上我在docker hub有说明：
https://hub.docker.com/r/80x86/filebrowser
参考"volume mapping: special tips for Synology NAS users" 部分。

```
/volume1 => /myfiles/volume1

/volume2 => /myfiles/volume2

...
```
`/myfiles` 不做映射。映射多个子目录到 /myfiles下的子目录，即可。

**Comment by jackcctse** [comment]
不完全是。union fs主要是用來管理storage pool，我用它把幾個不同容量的HDD掛載到同一掛載點來使用。配合snapraid來達到資料保護的陣列。
